### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol.be#4]
We will need a modern responsive template for the website.

**Comment by ghermans** [comment]
![prev](https://cloud.githubusercontent.com/assets/1594411/13724746/4067838e-e88f-11e5-80b8-dca1e9060377.png)

@Tjoosten what do you think about this one?

**Comment by Tjoosten** [comment]
Wil look after it tomorrow. I'm now on a working weekend from the belgian scouting federation

**Comment by ghermans** [comment]
## Services page 

![selection_134](https://cloud.githubusercontent.com/assets/1594411/13730022/9e0dc0b6-e943-11e5-9023-858370f633cb.png)

**Comment by Tjoosten** [comment]
@ghermans looks good. But what if we use a black color. on the first navigation navbar. (That one with languages.)

**Comment by ghermans** [comment]
## Contact page
![selection_135](https://cloud.githubusercontent.com/assets/1594411/13731400/9bfdcf0e-e967-11e5-89be-becfa73284eb.png)

**Comment by Tjoosten** [comment]
Push it to github?

**Comment by ghermans** [comment]
@Tjoosten will post it in a couple sec

**Comment by Tjoosten** [comment]
#7 is related to this and @ghermans Update on this plz
