### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol.be#8]
#### TODO

- [x] Create a contact controller 
- [x] Create a form
- [ ] Use all the data from the form to create a lead in SuiteCRM
 
#### Docs for creating a record in SuiteCRM.

http://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_6.5/Application_Framework/Web_Services/Examples/REST/PHP/Creating_or_Updating_a_Record/

**Comment by ghermans** [comment]
Todo list has been updated.

**Comment by Tjoosten** [comment]
@ghermans where can i find this list?

**Comment by ghermans** [comment]
@Tjoosten on the top of this page?

**Comment by Tjoosten** [comment]
@ghermans srry my bad.
